### ISSUE TITLE
Fails to build on Node v4.2.2, npm v3.4.1 Windows 7

### ISSUE THREAD

**Issue by rmilesson** [gaearon/disposables#5]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.4.1
3 info using node@v4.2.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle disposables@1.0.1~prebuild: disposables@1.0.1
6 silly lifecycle disposables@1.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle disposables@1.0.1~build: disposables@1.0.1
8 verbose lifecycle disposables@1.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle disposables@1.0.1~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Development\disposables-1.0.1\node_modules\.bin;%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Perl64\site\bin;C:\Perl64\bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\Microsoft Application Virtualization Client;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Sublime Text 3\;C:\Ruby22-x64\bin\;C:\Program Files\Perforce;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Program Files\Microsoft System Center 2012 R2\Service Manager\;C:\Program Files (x86)\Gource\cmd;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\username\AppData\Local\atom\bin;.bin;C:\Users\username\AppData\Roaming\npm
10 verbose lifecycle disposables@1.0.1~build: CWD: C:\Development\disposables-1.0.1
11 silly lifecycle disposables@1.0.1~build: Args: [ '/d /s /c', './scripts/build' ]
12 silly lifecycle disposables@1.0.1~build: Returned: code: 1  signal: null
13 info lifecycle disposables@1.0.1~build: Failed to exec build script
14 verbose stack Error: disposables@1.0.1 build: `./scripts/build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid disposables@1.0.1
16 verbose cwd C:\Development\disposables-1.0.1
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v4.2.2
20 error npm  v3.4.1
21 error code ELIFECYCLE
22 error disposables@1.0.1 build: `./scripts/build`
22 error Exit status 1
23 error Failed at the disposables@1.0.1 build script './scripts/build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the disposables package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./scripts/build
23 error You can get their info via:
23 error     npm owner ls disposables
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gaearon** [comment]
Maybe it doesn't build on Windows? Regardless, I'm not actively maintaining this code.
